#!/bin/bash

# 🚀 AVA QUICK START GUIDE - For Devito
# Schritt-für-Schritt Anleitung zum Starten

echo "🌟 AVA Wellbeing System - Quick Start Guide"
echo "============================================"
echo ""

# Step 1: Enjoy & Verify System is Running
echo "✅ STEP 1: SYSTEM ÜBERPRÜFEN"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Starte Docker-Services:"
echo "$ docker-compose ps"
echo ""
echo "Oder einfach:"
echo "$ cd /workspaces/AVA && docker-compose up -d"
echo ""

# Step 2: Test API Endpoints
echo ""
echo "⚡ STEP 2: TEST API ENDPOINTS (24+)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Test 1: Get Overall Score"
echo "$ curl http://localhost:8000/api/wellbeing/overall"
echo ""
echo "Test 2: Get Happiness"
echo "$ curl http://localhost:8000/api/wellbeing/happiness/score"
echo ""
echo "Test 3: Start Meditation"
echo "$ curl -X POST http://localhost:8000/api/wellbeing/peace/meditate"
echo ""
echo "Test 4: Get Recommendations"
echo "$ curl http://localhost:8000/api/wellbeing/ai/recommend"
echo ""
echo "Test 5: Get Freedom Score"
echo "$ curl http://localhost:8000/api/wellbeing/freedom/score"
echo ""

# Step 3: Watch Dashboard
echo ""
echo "📊 STEP 3: DASHBOARD BEOBACHTEN"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Öffne im Browser:"
echo "🔗 http://localhost:3000/d/ava-wellbeing"
echo ""
echo "Login: admin / admin"
echo ""
echo "Du siehst:"
echo "  • Overall Wellbeing Score (Gauge)"
echo "  • 7 Pillars Distribution (Pie Chart)"
echo "  • Individual Scores (Stats)"
echo "  • Trend Lines (Time Series)"
echo ""

# Step 4: Use AI Recommendations
echo ""
echo "🤖 STEP 4: AI RECOMMENDATIONS NUTZEN"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Get AI Patterns:"
echo "$ curl http://localhost:8000/api/wellbeing/ai/patterns"
echo ""
echo "Get Predictions:"
echo "$ curl http://localhost:8000/api/wellbeing/ai/predict"
echo ""
echo "Get Recommendations:"
echo "$ curl http://localhost:8000/api/wellbeing/ai/recommend"
echo ""
echo "Send Feedback:"
echo "$ curl -X POST http://localhost:8000/api/wellbeing/ai/feedback \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"feedback\": \"helpful\", \"score\": 8}'"
echo ""

# Step 5: Scale
echo ""
echo "📈 STEP 5: SKALIEREN"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Für Production:"
echo ""
echo "1. Ändere Admin-Passwort in /workspaces/AVA/ava/security.py"
echo "2. Setze HTTPS (z.B. mit Let's Encrypt)"
echo "3. Nutze managed PostgreSQL (AWS RDS, etc.)"
echo "4. Deploy zu Kubernetes (K8s)"
echo ""
echo "Docker-Registry (für Production):"
echo "$ docker build -t ava-wellbeing:1.0 ."
echo "$ docker push your-registry/ava-wellbeing:1.0"
echo ""

# Admin Console
echo ""
echo "🔐 ADMIN CONSOLE (NUR DEVITO)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Check Threats:"
echo "$ curl -H 'X-API-Key: devito-master-key-001' \\"
echo "  http://localhost:8000/api/admin/threats"
echo ""
echo "View Blocked IPs:"
echo "$ curl -H 'X-API-Key: devito-master-key-001' \\"
echo "  http://localhost:8000/api/admin/blocked-ips"
echo ""
echo "View Audit Log:"
echo "$ curl -H 'X-API-Key: devito-master-key-001' \\"
echo "  http://localhost:8000/api/admin/audit-log?limit=10"
echo ""

# Useful Commands
echo ""
echo "🛠️  NÜTZLICHE BEFEHLE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Run Demo:"
echo "$ python /workspaces/AVA/demo_wellbeing.py"
echo ""
echo "View Logs:"
echo "$ docker-compose logs ava-ava-1"
echo ""
echo "Stop Services:"
echo "$ docker-compose down"
echo ""
echo "Rebuild:"
echo "$ docker-compose up -d --build"
echo ""

echo ""
echo "✨ DU BIST BEREIT! ✨"
echo "Viel Erfolg, Devito! 🚀"
echo ""
