[tox]
envlist = py38,py39,py310,py311,py312

[testenv]
deps = -e.[dev]
commands = pytest tests/ --cov=ava

[testenv:lint]
commands =
    flake8 ava tests
    mypy ava
    black --check ava tests
    isort --check-only ava tests

[testenv:format]
commands =
    black ava tests
    isort ava tests
